// <auto-generated />
namespace ERPDAL.InventoryContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Inventory_AllEntities_31Mar2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inventory_AllEntities_31Mar2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310717010_Inventory_AllEntities_31-Mar-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
