// <auto-generated />
namespace ERPDAL.SalesAndDistributionContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SalesAndDistribution_Add_Model_Color_ModelColor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SalesAndDistribution_Add_Model_Color_ModelColor));
        
        string IMigrationMetadata.Id
        {
            get { return "202010270925276_SalesAndDistribution_Add_Model_Color_ModelColor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
