// <auto-generated />
namespace ERPDAL.ProductionContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Production_AllEntities_20April2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Production_AllEntities_20April2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202004200946043_Production_AllEntities_20-April-2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
